name: reco
description: 'Recycle Companion'

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

  tflite_flutter: ^0.9.1
  camera:
  image:
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^2.0.0
  dio: ^5.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
